services:
  #  web:
  #    build: .
  #    ports:
  #      - 8000:8000
  #    volumes:
  #      - .:/app
  mysql:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:3306
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    ports:
      - ${DB_PORT_PHPMYADMIN}:80

volumes:
  mysql:
